export const productReviews = [
  {
    rating: 5,
    review: 'Excelente producto',
    name: 'Diego Martínez',
    userTitle: 'Cliente satisfecho',
  },
  {
    rating: 4,
    review: 'Muy buen producto, llegó rápido y cumple con lo prometido.',
    name: 'Ana López',
    userTitle: 'Compradora frecuente',
  },
  {
    rating: 3,
    review: 'Es funcional pero esperaba una mejor calidad.',
    name: 'Carlos Ruiz',
    userTitle: 'Usuario ocasional',
  },
  {
    rating: 5,
    review: 'Me encanta, superó mis expectativas.',
    name: 'Valeria Sierra',
    userTitle: 'Cliente feliz',
  },
  {
    rating: 2,
    review: 'Tuve problemas con el envío, servicio regular.',
    name: 'Miguel Torres',
    userTitle: 'Primerizo',
  },
  {
    rating: 4,
    review: 'Buen balance precio-calidad.',
    name: 'Lucía Fernández',
    userTitle: 'Compradora habitual',
  },
  {
    rating: 5,
    review: 'Increíble, lo recomiendo totalmente.',
    name: 'José González',
    userTitle: 'Fan del producto',
  },
  {
    rating: 3,
    review: 'Normal, nada fuera de lo común.',
    name: 'Paola Castillo',
    userTitle: 'Consumidora',
  },
  {
    rating: 1,
    review: 'No funcionó para mí, decepcionante.',
    name: 'Roberto Díaz',
    userTitle: 'Cliente insatisfecho',
  },
  {
    rating: 4,
    review: 'Buena atención al cliente y producto adecuado.',
    name: 'Sofía Herrera',
    userTitle: 'Compradora online',
  },
  {
    rating: 5,
    review: 'Excelente producto, llegó en perfectas condiciones.',
    name: 'Andrea López',
    userTitle: 'Compradora frecuente',
  },
  {
    rating: 4,
    review: 'Buen producto, cumple con lo prometido.',
    name: 'Fernando Álvarez',
    userTitle: 'Usuario recurrente',
  },
  {
    rating: 3,
    review: 'Esperaba algo más, pero no está mal.',
    name: 'Gabriela Ortiz',
    userTitle: 'Consumidora',
  },
  {
    rating: 2,
    review: 'No cumplió con mis expectativas.',
    name: 'Luis Ramírez',
    userTitle: 'Cliente crítico',
  },
  {
    rating: 5,
    review: 'Funciona perfectamente, muy recomendable.',
    name: 'Juana Pérez',
    userTitle: 'Fanática de las compras',
  },
  {
    rating: 4,
    review: 'Buen servicio y atención, el producto es útil.',
    name: 'Manuel Vargas',
    userTitle: 'Comprador satisfecho',
  },
  {
    rating: 1,
    review: 'Producto defectuoso, no lo recomendaría.',
    name: 'Esteban Soto',
    userTitle: 'Cliente insatisfecho',
  },
  {
    rating: 5,
    review: 'Muy contento con la compra, superó mis expectativas.',
    name: 'Carmen Díaz',
    userTitle: 'Cliente feliz',
  },
  {
    rating: 3,
    review: 'Adecuado para el precio, nada sorprendente.',
    name: 'Rosa Muñoz',
    userTitle: 'Compradora ocasional',
  },
  {
    rating: 2,
    review: 'Presentó fallas a los pocos días.',
    name: 'Pedro Gutiérrez',
    userTitle: 'Usuario primerizo',
  },
  {
    rating: 4,
    review: 'La entrega fue rápida y el producto útil.',
    name: 'Laura Morales',
    userTitle: 'Compradora online',
  },
  {
    rating: 5,
    review: 'Me encanta, justo lo que buscaba.',
    name: 'Isabel Flores',
    userTitle: 'Clienta leal',
  },
  {
    rating: 3,
    review: 'En general está bien, aunque esperaba más funciones.',
    name: 'Pablo Castillo',
    userTitle: 'Usuario moderado',
  },
  {
    rating: 1,
    review: 'No lo volvería a comprar, mala experiencia.',
    name: 'Marta Ríos',
    userTitle: 'Consumidora exigente',
  },
  {
    rating: 5,
    review: 'Recomendado al 100%, muy buen producto.',
    name: 'Ángel Navarro',
    userTitle: 'Comprador repetidor',
  },
  {
    rating: 4,
    review: 'Funciona como esperaba, envío puntual.',
    name: 'Silvia Peña',
    userTitle: 'Compradora frecuente',
  },
  {
    rating: 2,
    review: 'El material no es de la mejor calidad.',
    name: 'Ramiro Jiménez',
    userTitle: 'Cliente crítico',
  },
  {
    rating: 5,
    review: 'Superó mis expectativas en todos los sentidos.',
    name: 'Natalia Soto',
    userTitle: 'Fan del producto',
  },
  {
    rating: 3,
    review: 'Mediocre, pero útil en situaciones concretas.',
    name: 'Oscar Torres',
    userTitle: 'Usuario casual',
  },
  {
    rating: 4,
    review: 'Buena relación calidad-precio.',
    name: 'Elena Ramírez',
    userTitle: 'Compradora reflexiva',
  },
  {
    rating: 5,
    review: 'Volveré a comprar sin dudas.',
    name: 'Diego Campos',
    userTitle: 'Cliente habitual',
  },
  {
    rating: 1,
    review: 'Mal desempeño, no lo recomiendo.',
    name: 'Paula Rosas',
    userTitle: 'Consumidora decepcionada',
  },
  {
    rating: 2,
    review: 'No está mal, pero hay mejores opciones.',
    name: 'Tomás Peña',
    userTitle: 'Comprador crítico',
  },
  {
    rating: 5,
    review: 'Perfecto, llegó antes de lo esperado.',
    name: 'Verónica Aguirre',
    userTitle: 'Compradora feliz',
  },
  {
    rating: 4,
    review: 'Me gustó el empaque y el producto.',
    name: 'Camila Salinas',
    userTitle: 'Nueva clienta',
  },
  {
    rating: 3,
    review: 'Regular, cumple con lo básico.',
    name: 'Jorge León',
    userTitle: 'Consumidor esporádico',
  },
  {
    rating: 5,
    review: 'La mejor compra del año.',
    name: 'Lucía Molina',
    userTitle: 'Cliente entusiasta',
  },
  {
    rating: 4,
    review: 'Satisfecho con el pedido.',
    name: 'Marcos Bravo',
    userTitle: 'Comprador regular',
  },
  {
    rating: 2,
    review: 'Se dañó rápido, esperaba más durabilidad.',
    name: 'Sandra Guzmán',
    userTitle: 'Consumidora crítica',
  },
  {
    rating: 1,
    review: 'Pésima calidad, no lo recomiendo en absoluto.',
    name: 'Gustavo Céspedes',
    userTitle: 'Cliente inconforme',
  },
  {
    rating: 4,
    review: 'Buen servicio y atención. Repetiría la compra.',
    name: 'Andrea Ríos',
    userTitle: 'Consumidora satisfecha',
  },
  {
    rating: 3,
    review: 'Un producto medianamente bueno, esperaba más.',
    name: 'Sergio Palacios',
    userTitle: 'Crítico ocasional',
  },
  {
    rating: 5,
    review: 'Simplemente espectacular. Lo recomiendo mucho.',
    name: 'Isabel Romero',
    userTitle: 'Compradora recurrente',
  },
  {
    rating: 2,
    review: 'No cumplió con lo descrito en la web.',
    name: 'Fernando Cabrera',
    userTitle: 'Cliente inquieto',
  },
  {
    rating: 4,
    review: 'Buena relación calidad-precio, todo correcto.',
    name: 'Estela Jiménez',
    userTitle: 'Compradora astuta',
  },
  {
    rating: 5,
    review: 'Superó mis expectativas totalmente.',
    name: 'Matías Herrera',
    userTitle: 'Usuario sorprendido',
  },
  {
    rating: 3,
    review: 'Razonable, aunque tiene margen de mejora.',
    name: 'Patricia Duarte',
    userTitle: 'Cliente objetiva',
  },
  {
    rating: 2,
    review: 'Demoró mucho en llegar.',
    name: 'Julio Zamora',
    userTitle: 'Comprador impaciente',
  },
  {
    rating: 5,
    review: 'Excelente calidad y empaque.',
    name: 'Mariana Flores',
    userTitle: 'Cliente exigente',
  },
  {
    rating: 4,
    review: 'En general satisfecho, aunque esperaba más accesorios.',
    name: 'Gabriel Mena',
    userTitle: 'Cliente detallista',
  },
  {
    rating: 1,
    review: 'Muy mala experiencia, no lo recomiendo.',
    name: 'Lorena Vázquez',
    userTitle: 'Compradora decepcionada',
  },
  {
    rating: 5,
    review: 'Funciona perfecto, muy feliz con la compra.',
    name: 'Raúl Morales',
    userTitle: 'Cliente entusiasta',
  },
  {
    rating: 4,
    review: 'Buen producto, atención al cliente excelente.',
    name: 'Nuria Sánchez',
    userTitle: 'Fan de la marca',
  },
  {
    rating: 3,
    review: 'Hace lo que promete, pero nada extraordinario.',
    name: 'Ignacio Alonso',
    userTitle: 'Cliente neutral',
  },
  {
    rating: 5,
    review: 'Entrega super rápida y producto impecable.',
    name: 'Bárbara Lugo',
    userTitle: 'Compradora feliz',
  },
  {
    rating: 2,
    review: 'La presentación no fue la mejor.',
    name: 'Álvaro Peña',
    userTitle: 'Comprador visual',
  },
  {
    rating: 4,
    review: 'Cumple con lo esencial.',
    name: 'Valentina Soto',
    userTitle: 'Consumidora práctica',
  },
  {
    rating: 5,
    review: 'Producto top, nada que criticar.',
    name: 'Tomás Muñoz',
    userTitle: 'Cliente leal',
  },
  {
    rating: 3,
    review: 'Para uso básico está bien.',
    name: 'Elisa Medina',
    userTitle: 'Compradora moderada',
  },
  {
    rating: 4,
    review: 'Precios accesibles y calidad decente.',
    name: 'Ricardo Fernández',
    userTitle: 'Cliente reflexivo',
  },
  {
    rating: 1,
    review: 'Nunca llegó el paquete.',
    name: 'Mónica Castillo',
    userTitle: 'Compradora frustrada',
  },
  {
    rating: 5,
    review: 'Excelente compra, lo volvería a comprar.',
    name: 'Pablo Núñez',
    userTitle: 'Comprador satisfecho',
  },
  {
    rating: 3,
    review: 'Tal vez lo vuelva a comprar, aunque hay mejores.',
    name: 'Sofía Ramos',
    userTitle: 'Cliente habitual',
  },
  {
    rating: 4,
    review: 'Buena experiencia de compra.',
    name: 'Marco Gil',
    userTitle: 'Comprador responsable',
  },
  {
    rating: 2,
    review: 'No era lo que esperaba, calidad justa.',
    name: 'Natalia Figueroa',
    userTitle: 'Consumidora escéptica',
  },
  {
    rating: 5,
    review: 'Muy buen diseño y fácil de usar.',
    name: 'Daniel Vargas',
    userTitle: 'Usuario conforme',
  },
  {
    rating: 4,
    review: 'Producto acorde al precio.',
    name: 'Florencia Rivero',
    userTitle: 'Compradora racional',
  },
  {
    rating: 5,
    review: 'Todo excelente. Lo recomiendo a todos.',
    name: 'Martín Reyes',
    userTitle: 'Fan satisfecho',
  },
  {
    rating: 3,
    review: 'Está bien, pero podría mejorar.',
    name: 'Cecilia Carranza',
    userTitle: 'Compradora exigente',
  },
  {
    rating: 2,
    review: 'Material de baja calidad.',
    name: 'Agustín Espinoza',
    userTitle: 'Cliente crítico',
  },
  {
    rating: 4,
    review: 'Muy útil, lo uso todos los días.',
    name: 'Liliana Pereyra',
    userTitle: 'Usuaria frecuente',
  },
];